title: Paula R. Curtis
email: prcurtis@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  This will eventually be a digital portfolio, but right now it is a sad baby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paularcurtis
github_username:  pr-curtis

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
